// var co=0;
var countJ;
function doAjaxWeather(co,nAdd){
    // countJ=0;
    // if(co==countJ){
    $.ajax({ 
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Tel-Aviv",
        crossDomain:true,
        dataType:"json",
        success:function(json_TelAvivYafo){
            countJ=0;
            if(co==countJ){
                createAllApi(json_TelAvivYafo,nAdd);
            }  
        }
    })
// }
// countJ=1;
// if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Jerusalem",
        crossDomain:true,
        dataType:"json",
        success:function(json_Jerusalem){
            countJ=1;
            if(co==countJ){
                createAllApi(json_Jerusalem,nAdd);
            }
        }
    })
// }
// countJ=2;
// if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Haifa",
        crossDomain:true,
        dataType:"json",
        success:function(json_Haifa){
            countJ=2;
            if(co==countJ){
                createAllApi(json_Haifa,nAdd);
            }      
        }
    })
// }
// countJ=3;
// if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Netanya",
        crossDomain:true,
        dataType:"json",
        success:function(json_Netanya){
            countJ=3;
            if(co==countJ){
                createAllApi(json_Netanya,nAdd);
            }
        }
    })
// }
// countJ=4;
//             if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Herzliya",
        crossDomain:true,
        dataType:"json",
        success:function(json_Herzliya){
            countJ=4;
            if(co==countJ){
                createAllApi(json_Herzliya,nAdd);
            }   
        }
    })
// }
// countJ=5;
//             if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Tiberias",
        crossDomain:true,
        dataType:"json",
        success:function(json_Tiberias){
            countJ=5;
            if(co==countJ){
                createAllApi(json_Tiberias,nAdd);
            }
        }
    })
// }
// countJ=6;
// if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Ashqelon",
        crossDomain:true,
        dataType:"json",
        success:function(json_Ashkelon){
            countJ=6;
            if(co==countJ){
                createAllApi(json_Ashkelon,nAdd);
            }
        }
    })
// }
// countJ=7;
// if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Eilat",
        crossDomain:true,
        dataType:"json",
        success:function(json_Eilat){
            countJ=7;
            if(co==countJ){
                createAllApi(json_Eilat,nAdd);
            }
        }
    })
// }
// countJ=8;
//             if(co==countJ){
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Accho",
        crossDomain:true,
        dataType:"json",
        success:function(json_Accho){
            countJ=8;
            if(co==countJ){
                createAllApi(json_Accho,nAdd);
            }
        }
    })
// }
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Natsrat",
        crossDomain:true,
        dataType:"json",
        success:function(json_Nazareth){
            countJ=9;
            if(co==countJ){
                createAllApi(json_Nazareth,nAdd);
            }
        }
    })
// }
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Caesarea",
        crossDomain:true,
        dataType:"json",
        success:function(json_Caesarea){
            countJ=10;
            if(co==countJ){
                createAllApi(json_Caesarea,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Zefat",
        crossDomain:true,
        dataType:"json",
        success:function(json_Zefat){
            countJ=11;
            if(co==countJ){
                createAllApi(json_Zefat,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Mizpe-Ramon",
        crossDomain:true,
        dataType:"json",
        success:function(json_MizpeRamon){
            countJ=12;
            if(co==countJ){
                createAllApi(json_MizpeRamon,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Beit-Shean",
        crossDomain:true,
        dataType:"json",
        success:function(json_BetShean){
            countJ=13;
            if(co==countJ){
                createAllApi(json_BetShean,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=En-Gedi",
        crossDomain:true,
        dataType:"json",
        success:function(json_EnGedi){
            countJ=14;
            if(co==countJ){
                createAllApi(json_EnGedi,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Rosh-Pinna",
        crossDomain:true,
        dataType:"json",
        success:function(json_RoshPinna){
            countJ=15;
            if(co==countJ){
                createAllApi(json_RoshPinna,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Tel-Hazor",
        crossDomain:true,
        dataType:"json",
        success:function(json_Hazor){
            countJ=16;
            if(co==countJ){
                createAllApi(json_Hazor,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Holon",
        crossDomain:true,
        dataType:"json",
        success:function(json_Holon){
            countJ=17;
            if(co==countJ){
                createAllApi(json_Holon,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Kisra",
        crossDomain:true,
        dataType:"json",
        success:function(json_Kisra){
            countJ=18;
            if(co==countJ){
                createAllApi(json_Kisra,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Ramla",
        crossDomain:true,
        dataType:"json",
        success:function(json_Ramla){
            countJ=19;
            if(co==countJ){
                createAllApi(json_Ramla,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Ashdod",
        crossDomain:true,
        dataType:"json",
        success:function(json_Ashdod){
            countJ=20;
            if(co==countJ){
                createAllApi(json_Ashdod,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Zikhron-Yaaqov",
        crossDomain:true,
        dataType:"json",
        success:function(json_ZikhronYaaqov){
            countJ=21;
            if(co==countJ){
                createAllApi(json_ZikhronYaaqov,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Kefar-Tavor",
        crossDomain:true,
        dataType:"json",
        success:function(json_KefarTavor){
            countJ=22;
            if(co==countJ){
                createAllApi(json_KefarTavor,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Bnei-Brak",
        crossDomain:true,
        dataType:"json",
        success:function(json_BneiBrak){
            countJ=23;
            if(co==countJ){
                createAllApi(json_BneiBrak,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Beersheba",
        crossDomain:true,
        dataType:"json",
        success:function(json_Beersheba){
            countJ=24;
            if(co==countJ){
                createAllApi(json_Beersheba,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Isfiya",
        crossDomain:true,
        dataType:"json",
        success:function(json_Isfiya){
            countJ=25;
            if(co==countJ){
                createAllApi(json_Isfiya,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Bat-Yam",
        crossDomain:true,
        dataType:"json",
        success:function(json_BatYam){
            countJ=26;
            if(co==countJ){
                createAllApi(json_BatYam,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Nahariya",
        crossDomain:true,
        dataType:"json",
        success:function(json_Nahariya){
            countJ=27;
            if(co==countJ){
                createAllApi(json_Nahariya,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Metulla",
        crossDomain:true,
        dataType:"json",
        success:function(json_Metulla){
            countJ=28;
            if(co==countJ){
                createAllApi(json_Metulla,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Daliyat-El-Karmil",
        crossDomain:true,
        dataType:"json",
        success:function(json_DaliyatElKarmil){
            countJ=29;
            if(co==countJ){
                createAllApi(json_DaliyatElKarmil,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Tarshihah",
        crossDomain:true,
        dataType:"json",
        success:function(json_Maalot){
            countJ=30;
            if(co==countJ){
                createAllApi(json_Maalot,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Yad-Mordekhay",
        crossDomain:true,
        dataType:"json",
        success:function(json_YadMordekhay){
            countJ=31;
            if(co==countJ){
                createAllApi(json_YadMordekhay,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Qiryat-Shemona",
        crossDomain:true,
        dataType:"json",
        success:function(json_QiryatShemona){
            countJ=32;
            if(co==countJ){
                createAllApi(json_QiryatShemona,nAdd);
            }
        }
    })          
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Yanuh",
        crossDomain:true,
        dataType:"json",
        success:function(json_Yanuh){
            countJ=33;
            if(co==countJ){
                createAllApi(json_Yanuh,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Kinneret",
        crossDomain:true,
        dataType:"json",
        success:function(json_Kinneret){
            countJ=34;
            if(co==countJ){
                createAllApi(json_Kinneret,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Sede-Boqer",
        crossDomain:true,
        dataType:"json",
        success:function(json_SedeBoqer){
            countJ=35;
            if(co==countJ){
                createAllApi(json_SedeBoqer,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Arad",
        crossDomain:true,
        dataType:"json",
        success:function(json_Arad){
            countJ=36;
            if(co==countJ){
                createAllApi(json_Arad,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Qazrin",
        crossDomain:true,
        dataType:"json",
        success:function(json_Katzrin){
            countJ=37;
            if(co==countJ){
                createAllApi(json_Katzrin,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=En-Hod",
        crossDomain:true,
        dataType:"json",
        success:function(json_EnHod){
            countJ=38;
            if(co==countJ){
                createAllApi(json_EnHod,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Maghar",
        crossDomain:true,
        dataType:"json",
        success:function(json_Maghar){
            countJ=39;
            if(co==countJ){
                createAllApi(json_Maghar,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Yirka",
        crossDomain:true,
        dataType:"json",
        success:function(json_Yirka){
            countJ=40;
            if(co==countJ){
                createAllApi(json_Yirka,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Hurfeish",
        crossDomain:true,
        dataType:"json",
        success:function(json_Hurfeish){
            countJ=41;
            if(co==countJ){
                createAllApi(json_Hurfeish,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Jatt",
        crossDomain:true,
        dataType:"json",
        success:function(json_Jatt){
            countJ=42;
            if(co==countJ){
                createAllApi(json_Jatt,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Abu-Sinan",
        crossDomain:true,
        dataType:"json",
        success:function(json_AbuSinan){
            countJ=43;
            if(co==countJ){
                createAllApi(json_AbuSinan,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Beit-Jann",
        crossDomain:true,
        dataType:"json",
        success:function(json_BeitJann){
            countJ=44;
            if(co==countJ){
                createAllApi(json_BeitJann,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Kisra",
        crossDomain:true,
        dataType:"json",
        success:function(json_Kisra){
            countJ=45;
            if(co==countJ){
                createAllApi(json_Kisra,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Sajur",
        crossDomain:true,
        dataType:"json",
        success:function(json_Sajur){
            countJ=46;
            if(co==countJ){
                createAllApi(json_Sajur,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Shfaram",
        crossDomain:true,
        dataType:"json",
        success:function(json_Shfaram){
            countJ=47;
            if(co==countJ){
                createAllApi(json_Shfaram,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Deganya-Alef",
        crossDomain:true,
        dataType:"json",
        success:function(json_DeganyaAlef){
            countJ=48;
            if(co==countJ){
                createAllApi(json_DeganyaAlef,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Julis",
        crossDomain:true,
        dataType:"json",
        success:function(json_Julis){
            countJ=49;
            if(co==countJ){
                createAllApi(json_Julis,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Hanita",
        crossDomain:true,
        dataType:"json",
        success:function(json_Hanita){
            countJ=50;
            if(co==countJ){
                createAllApi(json_Hanita,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Kfar-Yasif",
        crossDomain:true,
        dataType:"json",
        success:function(json_KafrYasif){
            countJ=51;
            if(co==countJ){
                createAllApi(json_KafrYasif,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Arraba",
        crossDomain:true,
        dataType:"json",
        success:function(json_Arraba){
            countJ=52;
            if(co==countJ){
                createAllApi(json_Arraba,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Yizre`El",
        crossDomain:true,
        dataType:"json",
        success:function(json_Yizreel){
            countJ=53;
            if(co==countJ){
                createAllApi(json_Yizreel,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Tel-Hai",
        crossDomain:true,
        dataType:"json",
        success:function(json_TelHai){
            countJ=54;
            if(co==countJ){
                createAllApi(json_TelHai,nAdd);
            }
        }
    }) 
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Gush-Halab",
        crossDomain:true,
        dataType:"json",
        success:function(json_GushHalab){
            countJ=55;
            if(co==countJ){
                createAllApi(json_GushHalab,nAdd);
            }
        }
    })
    $.ajax({
        url:"http://api.apixu.com/v1/forecast.json?key=d6b2c6556bd44118a0d151443192001&q=Abu-Ghosh",
        crossDomain:true,
        dataType:"json",
        success:function(json_AbuGhosh){
            countJ=56;
            if(co==countJ){
                createAllApi(json_AbuGhosh,nAdd);
            }
        }
    })
    
    
}